
# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
  publish = "_site/"
  command = "npm run build"

# https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
  from = "/index/"
  to = "/recipes/"
  status = 302
  force = true
  # query = {path = ":path"}
  # conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
  # headers = {X-From = "Netlify"}
  # signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/wp-admin/*"
  to = "https://content.dollyskettle.com/wp-admin/:splat"
  status = 302

# https://docs.netlify.com/routing/redirects/rewrites-proxies/#proxy-to-another-service
[[redirects]]
  from = "/wp-content/*"
  to = "https://content.dollyskettle.com/wp-content/:splat"
  status = 200
  force = true
